name: FPI
favicon: null
layout_spectrum: 0.7312742630019784
typography_spectrum: 0.8924159456510097
title: 'Integrated Marketing Communications & Campaign Management'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.35849390691146255
  lightness: 0.8200460246298462
  saturation: 0.38091301964595914
  rhythmicContrast: 0.9454890645574778
purpose: []
