name: Fred Page Incorporated
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8924159456510097
title: 'Integrated Marketing Communications & Campaign Management'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#29282e'
    - '#ffffff'
    - '#9f9890'
    - '#4e4e51'
    - '#cacacb'
  brandStrength: 0.5
  lightness: 0.8200460246298462
  saturation: 0.38091301964595914
  rhythmicContrast: 0.9454890645574778
purpose: []
